DjangoLoginDemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
]

login/urls.py
from django.urls import path

from login import views

app_name = 'login'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

login/models.py
import hashlib

from django.db import models


class User(models.Model):
    """用户实体类"""
    username = models.CharField(max_length=32, unique=True)
    password = models.CharField(max_length=40)

    def __str__(self):
        return self.username

    @classmethod
    def encrypt_password(cls, password):
        """使用SHA-1加密密码，返回长度为40的加密后的字符串。"""
        return hashlib.sha1(password.encode()).hexdigest()

login/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from login.models import User


def index(request):
    return render(request, 'login/index.html', {'message': request.GET.get('message')})


@require_http_methods(['GET', 'POST'])
def register(request):
    if request.method == 'GET':
        return render(request, 'login/register.html')
    username = request.POST['username']
    password = User.encrypt_password(request.POST['password'])
    if User.objects.filter(username=username).exists():
        return render(request, 'login/register.html', {'error_message': '用户名已存在'})
    User.objects.create(username=username, password=password)
    return HttpResponseRedirect(reverse('login:index') + '?message=注册成功')


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'GET':
        return render(request, 'login/login.html')
    username = request.POST['username']
    password = User.encrypt_password(request.POST['password'])
    try:
        user = User.objects.get(username=username)
        if user.password == password:
            request.session['username'] = user.username
            return redirect('login:index')
        else:
            return render(request, 'login/login.html', {'error_message': '用户名或密码错误'})
    except User.DoesNotExist:
        return render(request, 'login/login.html', {'error_message': '用户名或密码错误'})


def logout(request):
    if 'username' in request.session:
        del request.session['username']
    return HttpResponseRedirect(reverse('login:index') + '?message=注销成功')

login/templates/login/base.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block script %}{% endblock %}
</head>
<body>
<div id="content">
    {% block header %}<h1>Django Login Demo</h1>{% endblock %}
    <hr>
    {% block content %}{% endblock %}
    <hr>
    <footer>
        <small>Author: <a href="https://github.com/ZZy979">ZZy</a></small>
    </footer>
</div>
</body>
</html>

login/templates/login/index.html
{% extends 'login/base.html' %}

{% block title %}首页{% endblock %}

{% block script %}
{% if message %}
    <script>alert('{{ message }}')</script>
{% endif %}
{% endblock %}

{% block content %}
{% if request.session.username %}
    <nav>
        <a href="{% url 'login:logout' %}">注销</a>
    </nav>
    <p>欢迎，{{ request.session.username }}！</p>
{% else %}
    <nav>
        <a href="{% url 'login:login' %}">登录</a> |
        <a href="{% url 'login:register' %}">注册</a>
    </nav>
    <p>欢迎！</p>
{% endif %}
{% endblock %}

login/templates/login/login.html
{% extends 'login/base.html' %}

{% block title %}用户登录{% endblock %}

{% block header %}<h1>用户登录</h1>{% endblock %}

{% block content %}
{% if error_message %}<p style="color: red">{{ error_message }}</p>{% endif %}
<form action="{% url 'login:login' %}" method="post">
    {% csrf_token %}
    <label for="username-input">用户名</label>
    <input id="username-input" type="text" name="username"
           pattern="[0-9A-Za-z_]+" maxlength="32" required>
    <br>
    <label for="password-input">密码</label>
    <input id="password-input" type="password" name="password" maxlength="32" required>
    <br>
    <input type="submit" value="登录">
</form>
{% endblock %}

login/templates/login/register.html
{% extends 'login/base.html' %}

{% block title %}用户注册{% endblock %}

{% block header %}<h1>用户注册</h1>{% endblock %}

{% block content %}
{% if error_message %}<p style="color: red">{{ error_message }}</p>{% endif %}
<form action="{% url 'login:register' %}" method="post">
    {% csrf_token %}
    <label for="username-input">用户名</label>
    <input id="username-input" type="text" name="username"
           pattern="[0-9A-Za-z_]+" maxlength="32"
           placeholder="仅字母、数字和下划线" required>
    <br>
    <label for="password-input">密码</label>
    <input id="password-input" type="password" name="password" maxlength="32" required>
    <br>
    <input type="submit" value="注册">
</form>
{% endblock %}